import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import StoreProvider from "./store-provider";
import { Roboto } from "next/font/google";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const roboto = Roboto({
  subsets: ["latin"], // Choose the subset for your project
  weight: ["400", "700"], // Specify weights as needed
  variable: "--font-roboto", // Define a custom CSS variable
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StoreProvider>
        <body className={`${roboto.variable} antialiased`}>{children}</body>
      </StoreProvider>
    </html>
  );
}
